language: rust
rust:
  - stable
  - nightly
  - 1.14.0  # shipping debian version 2018 03
cache: cargo

script:
  - cargo build --verbose --features strict
  - cargo test --verbose --features strict

jobs:
  include:
  - stage: fuzz
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y binutils-dev libunwind8-dev
    rust: stable
    script: cd fuzz && cargo update && cargo test --verbose && ./travis-fuzz.sh
