language: rust
rust:
  - stable
  - nightly
  - 1.36.0  # project wide min version
cache: cargo

script:
  - cargo build --verbose --no-default-features --features strict
  - cargo build --verbose --features strict
  - cargo test --verbose --no-default-features --features strict
  - cargo test --verbose --features strict

jobs:
  include:
  - stage: best practices
    rust: stable
    install:
      - rustup component add rustfmt
      - rustup component add clippy
    script:
      - rustfmt --check src/lib.rs
      - cargo clippy -- -D warnings
  - stage: fuzz
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y binutils-dev libunwind8-dev
    rust: stable
    script: cd fuzz && cargo update && cargo test --verbose && ./travis-fuzz.sh
